### ISSUE TITLE
weibo代码使用询问

### ISSUE THREAD

**Issue by Z244830811** [enrichyourlife/weibo#1]
您好！我想获取北京和武汉两个城市用户的微博签到数据，可以直接使用您的代码吗？位置范围应该在哪里修改呢？用户id是指要爬取的用户对象id还是我个人使用的id？谢谢回答

**Comment by enrichyourlife** [comment]
您好，可以获取的，位置范围需要改代码中的获取城市代码部分 ，目前程序给出了上海和成都两个地区的城市代码，其他地区需要后续添加，用户id是指爬取到的用户微博id，使用过程有疑问可以添加我qq交流 321041381，
